import Head from 'next/head';
import Link from 'next/link';
import ChartComponent from '../components/chart';

export default function Home() {
  return (
    <>
      <Head>
        <title>Kjellcase</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <Link rel="icon" href="/excel.ico" />
      </Head>
      <main>
        <ChartComponent />
      </main>
    </>
  );
}
